import { getCssText } from "@/styles"
import { globalStyles } from "@/styles/global"
import { Roboto } from "next/font/google"
import Head from "next/head"

export const metadata = {
  title: 'Ignite Shop',
  description: 'Generated by Next.js',
}

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

globalStyles()

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <head>
        <style id="stitches" dangerouslySetInnerHTML={{ __html: getCssText() }} />
      </head>
      <body>
        <main className={roboto.className}>
          {children}
        </main>
      </body>
    </html>
  )
}
